/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Eduardo
 */
public class panelEjercicio extends javax.swing.JPanel {

    /**
     * Creates new form panelAlimento
     */
    public panelEjercicio() {
        initComponents();
        this.setSize(520,440);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 47, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("Nombre del Ejercicio");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 250, 50));

        labelDescripcion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        labelDescripcion.setText("Esta es la descripcion del alimento");
        add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 270, 80));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("A este label se añade la imagen");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 200, 130));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
