/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Patrones.Database;
import Patrones.Usuario;
import javax.swing.JScrollPane;

/**
 *
 * @author Eduardo
 */
public class panelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form panelRegistro
     */
    Usuario u;
    public panelRegistro() {
        initComponents();
        this.setSize(520,440);
        //areaAlimento.append("hola");
        //JScrollPane pane =  new JScrollPane(areaAlimento,JScrollPane.VERTICAL_SCROLLBAR_NEVER, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        //areaAlimento.setEnabled(true);
        //areaAlimento.setEditable(true);
    }
    
    public void setUser(Usuario u){
        this.u = u;
    }
    
    public void setData(){
        this.jTable1.setModel(Database.getInstance().getLogPorUser(u.getId()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(36, 47, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre1.setText("Registro de Actividad");
        add(labelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 250, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 400, 270));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNombre1;
    // End of variables declaration//GEN-END:variables
}
