/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Eduardo
 */
public class panelAlimento extends javax.swing.JPanel {

    /**
     * Creates new form panelAlimento
     */
    public panelAlimento() {
        initComponents();
        this.setSize(520,440);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelCalorias = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 47, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("Nombre del Alimento");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 250, 50));

        labelDescripcion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        labelDescripcion.setText("Esta es la descripcion del alimento");
        add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 270, 80));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calorias: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        labelCalorias.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelCalorias.setForeground(new java.awt.Color(255, 255, 255));
        labelCalorias.setText("Int con la cantidad de calorias");
        add(labelCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCalorias;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
